spring:
  application:
    name: microchelik2

server:
  port: 4424

eureka:
  client:
    service-url:
      defaultZone: https://reg-serv.herokuapp.com/eureka/

refresh:
  word: krek

putin:
  huilo: tochno
