spring:
  application:
    name: microchelik2

server:
  port: 4454

eureka:
  client:
    service-url:
      defaultZone: https://reg-serv.herokuapp.com/eureka/

refresh:
  word: Kekes

putin:
  huilo: true
